# GitHub Sponsors (uncomment if you have one)
# github: gyarsilalsolanki011

# Supported funding platforms:
# - github
# - patreon
# - open_collective
# - ko_fi
# - tidelift
# - community_bridge
# - liberapay
# - issuehunt
# - otechie
# - custom: array of URLs

# Example setup for your Make_Attendance app
patreon: gyarsilal_solanki
ko_fi: gyarsilal
liberapay: gyarsilalsolanki011

# Custom links (you can add UPI or BuyMeACoffee)
custom:
  - "https://www.buymeacoffee.com/gyarsilal"
  - "https://rzp.io/l/make_attendance_support" # Razorpay payment link
  - "upi://pay?pa=gyarsilal@upi&pn=Gyarsilal%20Solanki"
